<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Haithams-Laptop" failures="1" tests="1" name="TestWithParams3" time="0.009" errors="0" timestamp="2022-08-27T12:10:28 IDT">
  <testcase classname="pkgTest.numberTest" name="testCalculator" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [4]
at pkgTest.numberTest.testCalculator(numberTest.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testCalculator -->
</testsuite> <!-- TestWithParams3 -->
